#!/bin/bash
# File: common_run_utils.sh

# Global interpreter configuration
PYTHON_INTERPRETER="python3"
LATEX_INTERPRETER="pdflatex"

: "${CURRENT_DEPTH:=1}"   # assigne only if not alredy difined
export CURRENT_DEPTH


# Function to display usage/help
show_help() {
  echo "Usage: $0 /path/to/gpyro [OPTIONS] [ARGS...]"
  echo ""
  echo "Options:"
  echo "  --full                     Run all test cases even the computation expensive ones. Default=false"
  echo "  --not-run-cases            Do not run the cases; this will only generate the PDF report."
  echo "  --compute-analytical       Recompute the analytical solution (for cases that have one). Default=false"
  echo "  --no-pdf-report            Disable PDF report generation. Default=false"
  echo "  --pdf-depth-limit=<n>      Limit PDF generation to depth <n>. Default=1"
  echo "  --help                     Display this help message."
  echo ""
}



# Function to parse command-line arguments and set related flags
parse_common_args() {
  POSITIONAL_ARGS=()

  # Default flag values (can be overridden by user options)
  RUN_ANALYTICAL=false
  RUN_PDF=true
  FULL_RUN=false
  RUN_CASES=true
  PDF_DEPTH_LIMIT=1

  # Loop through all command-line arguments
  for arg in "$@"; do
    case $arg in
      --full)
        FULL_RUN=true
        shift
        ;;
      --not-run-cases)
        RUN_CASES=false
        shift
        ;;
      --compute-analytical)
        RUN_ANALYTICAL=true
        shift
        ;;
      --no-pdf-report)
        RUN_PDF=false
        shift
        ;;
      --pdf-depth-limit=*)
        PDF_DEPTH_LIMIT="${arg#*=}"
        shift
        ;;
      --help)
        show_help
        exit 0
        ;;
      --*)  # Catch unknown options
        echo "Error: unknown option '$arg'"
        echo ""
        show_help
        exit 1
        ;;
      *)
        POSITIONAL_ARGS+=("$arg")
        shift
        ;;
    esac
  done

  # Restore positional arguments and export them for caller scripts
  set -- "${POSITIONAL_ARGS[@]}"
  export PARSED_ARGS=("$@")

  # Inform the user if all cases are skipped
  if [ "$RUN_CASES" = false ]; then
    echo "[SKIP] Execution of all cases (RUN_CASES=false)"
  fi
}


# Function to validate the GPYRO executable path
check_gpyro_executable() {
  if [ -n "$1" ]; then
    GPYRO="$1"
  else
    if [ -z "$GPYRO" ]; then
      echo "Error: No gpyro binary provided."
      show_help
      exit 1
    fi
  fi

  # Ensure the path points to an executable
  if [ ! -x "$GPYRO" ]; then
    echo "Error: The specified path '$GPYRO' is not a valid gpyro executable."
    show_help
    exit 1
  fi
}


# Color definitions for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color (reset)


check_smokeview_executable() {
  # If already checked once, don't check again (just export SKIP_SMOKEVIEW as is)
  if [ "${CHECKED_SMOKEVIEW:-false}" = true ]; then
    return
  fi


  # Mark as checked
  export CHECKED_SMOKEVIEW=true

  if [ -z "$smokeview" ]; then
    echo "Warning: Environment variable 'smokeview' is not defined."
    echo "To enable visual post-processing of the 3D simulations that use Smokeview, define it like this:"
    echo "  export smokeview=/Your/valid/path/to/smokeview.exe"
    printf "Do you want to use Smokeview? (y/n): "
    read choice
    if [[ "$choice" =~ ^[Yy]$ ]]; then
      echo "Exiting. Please define the 'smokeview' variable and rerun the script."
      exit 1
    fi
    export SKIP_SMOKEVIEW=true
  elif [ ! -x "$smokeview" ]; then
    echo "Error: '$smokeview' is not an executable."
    echo "To enable visual post-processing of the 3D simulations that use Smokeview, define it like this:"
    echo "  export smokeview=/Your/valid/path/to/smokeview.exe"
    printf "Do you want to use Smokeview? (y/n): "
    read choice
    if [[ "$choice" =~ ^[Yy]$ ]]; then
      echo "Exiting. Please fix the path to Smokeview and rerun the script."
      exit 1
    fi
    export SKIP_SMOKEVIEW=true
  else
    export SKIP_SMOKEVIEW=false
  fi
}



# Fonction générique pour lancer un cas
run_case() {
  local case_dir="$1"
  local script_name="${2:-run.sh}"  # par défaut run.sh

  ((CURRENT_DEPTH++))

  if [ "$RUN_CASES" = true ]; then
    (
      cd "$case_dir" || exit 1
      bash "$script_name" "$GPYRO" "${ARGS[@]}"
    )
  fi

  ((CURRENT_DEPTH--))
}


generate_latex_paths()
  {
  local ROOT_DIR="${1:-$(pwd)}"
  local OUTPUT_FILE="${ROOT_DIR}/path.tex"

  echo "% File automatically generated by generate_latex_path function in run_utils.sh" > "$OUTPUT_FILE"
  echo "% Path definitions with folder prefix" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"

  for dir in "$ROOT_DIR"/*/; do
    dir_name=$(basename "$dir")
    texfile=$(find "$dir" -maxdepth 1 -type f -name '*.tex' | head -n 1)
    echo "$texfile"
    if [[ -f "$texfile" ]]; then
      # Read line by line, removing comments and spaces
      grep '\\newcommand' "$texfile" | while read -r line; do
        # Remove everything after the first % (comment)
        line_no_comment=$(echo "$line" | sed 's/%.*//')
        # Remove leading/trailing whitespace
        line_clean=$(echo "$line_no_comment" | sed 's/^[ \t]*//;s/[ \t]*$//')

        # Extract command name and path value
        cmd_name=$(echo "$line_clean" | sed -n 's/\\newcommand{\(\\[^}]*\)}{[^}]*}/\1/p')
        path_value=$(echo "$line_clean" | sed -n 's/\\newcommand{\\[^}]*}{\([^}]*\)}/\1/p')

        # If both were successfully captured
        if [[ -n "$cmd_name" && -n "$path_value" ]]; then
          new_path="${dir_name}/${path_value}"
          echo "\\newcommand{${cmd_name}}{${new_path}}" >> "$OUTPUT_FILE"
        fi
      done
    fi
  done

  echo "path.tex file generated successfully."
}


compile_pdf_report() {
  local mode="${1:-simple}"  # default to 'simple'

  if [ "$RUN_PDF" != true ]; then
    return
  fi

  # ne compiler qu'aux niveaux < limite
  if [ "$CURRENT_DEPTH" -gt "$PDF_DEPTH_LIMIT" ]; then
    echo "(skip PDF at depth=$CURRENT_DEPTH ; limit=$PDF_DEPTH_LIMIT)"
    return
  fi

  echo ""
  echo "--- PDF Compilation ---"

  if [ -z "$LATEX_CMD" ] || [ -z "$LATEX_FILE" ]; then
    echo -e "${RED}LATEX_CMD or LATEX_FILE is not defined. Skipping PDF compilation.${NC}"
    return
  fi

  PDF_FILE="${SCRIPT_DIR}/${LATEX_FILE}.pdf"
  BACKUP_PDF="${PDF_FILE}.bak"
  LOG_FILE="${SCRIPT_DIR}/${LATEX_FILE}.log"

  # Backup previous PDF
  [ -f "$PDF_FILE" ] && mv "$PDF_FILE" "$BACKUP_PDF"



  if [ "$mode" = "bibtex" ]; then
    echo "[1/3] pdflatex"
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
    echo "[2/3] bibtex"
    (cd "$SCRIPT_DIR" && bibtex "$LATEX_FILE" > /dev/null)
    echo "[3/3] pdflatex x2"
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
  
  elif [ "$mode" = "book" ]; then
    echo "[0] Run generate_path.sh script"
    generate_latex_paths
    echo "[1/3] pdflatex"
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
    echo "[2/3] bibtex"
    (cd "$SCRIPT_DIR" && bibtex "$LATEX_FILE" > /dev/null)
    echo "[3/3] pdflatex x2"
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null

  else
    echo "[1] pdflatex x2"
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
    "$LATEX_INTERPRETER" -interaction=nonstopmode -file-line-error -output-directory="$SCRIPT_DIR" "$LATEX_CMD" > /dev/null
  fi



  # Check result
  if [ ! -f "$PDF_FILE" ] || [ "$PDF_FILE" -ot "$BACKUP_PDF" ]; then
    echo -e "${RED}PDF compilation failed: no new PDF generated. Check the log file.${NC}"
    [ -f "$BACKUP_PDF" ] && mv "$BACKUP_PDF" "$PDF_FILE"
  else
    [ -f "$BACKUP_PDF" ] && rm "$BACKUP_PDF"
    if grep -q " Error:" "$LOG_FILE"; then
      echo -e "${YELLOW}PDF compiled with LaTeX errors. Check the log file.${NC}"
    else
      echo -e "${GREEN}PDF compiled successfully.${NC}"
    fi
  fi
}




# Write execution status to the central status report file
write_status_report() {
  SCRIPT_DIR="$1"
  POST_EXIT_CODE="$2"

  # Traverse upward until the 'Verification' directory is found
  VERIFICATION_DIR="$SCRIPT_DIR"
  while [ "$(basename "$VERIFICATION_DIR")" != "Verification" ] && [ "$VERIFICATION_DIR" != "/" ]; do
    VERIFICATION_DIR="$(dirname "$VERIFICATION_DIR")"
  done

  # If 'Verification' folder is not found, return error
  if [ "$(basename "$VERIFICATION_DIR")" != "Verification" ]; then
    echo "Error: Unable to locate 'Verification' directory."
    return 2
  fi

  STATUS_FILE="$VERIFICATION_DIR/status_report.txt"
  CASE_PATH="$(realpath --relative-to="$VERIFICATION_DIR" "$SCRIPT_DIR")"
  TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"

  # Initialize status file if it does not exist
  if [ ! -f "$STATUS_FILE" ]; then
    echo "Verification status report" > "$STATUS_FILE"
    echo "==========================" >> "$STATUS_FILE"
    echo "" >> "$STATUS_FILE"
  fi
  echo ""
  # Append test result with timestamp to the status report
  if [ "$POST_EXIT_CODE" -eq 0 ]; then
    printf "[OK]     %s    (%s)\n" "$CASE_PATH" "$TIMESTAMP" >> "$STATUS_FILE"
    echo -e "${GREEN}✔ VALIDATION PASSED.${NC}"
  else
    printf "[FAILED] %s    (%s)\n" "$CASE_PATH" "$TIMESTAMP" >> "$STATUS_FILE"
    echo -e "${RED}✘ VALIDATION FAILED.${NC}"
  fi
}

