MODULE GPYRO_INIT

USE PREC
USE GPYRO_VARS
USE GPYRO_FUNCS
USE GPYRO_IO
USE GPYRO_MASS, ONLY : RHOOFT
USE GPYRO_MESH, ONLY : INIT_MESH

IMPLICIT NONE

CONTAINS

!******************************************************************************
SUBROUTINE DEALLOCATE_GPYRO
!******************************************************************************

IF (ALLOCATED(GPM   )) DEALLOCATE(GPM   )

!******************************************************************************
END SUBROUTINE DEALLOCATE_GPYRO
!******************************************************************************

!******************************************************************************
SUBROUTINE ALLOCATE_GPYRO(IMESH)
!******************************************************************************

INTEGER, INTENT(IN) :: IMESH
INTEGER :: NGSPEC,NSSPEC,NRXN,NHGRXN
INTEGER :: I, STR_SIZE
INTEGER :: NCELLZ, NCELLX , NCELLY
TYPE (GPYRO_MESH_TYPE), POINTER :: M

IF (.NOT. ALLOCATED (GPM)) ALLOCATE(GPM(GPG%NUM_GPYRO_MESHES))

! Initialize system clock
IF (IGPYRO_TYPE .EQ. 2) THEN !If this is an FDS run initialize the system clock here
   CALL SYSTEM_CLOCK(COUNT_RATE=CLOCK_COUNT_RATE)
   CALL SYSTEM_CLOCK(COUNT_MAX=CLOCK_COUNT_MAX)
ENDIF

G => GPM(IMESH)

! This is ALLOCATABLE (not POINTER) so if it's already allocated then we've already done
! this mesh so return
IF (ALLOCATED(G%CONV_INFO%CONVERGED_YIS)) RETURN

CALL ALLOCATE_MESH(IMESH)
M => G%MESH

!Allocate NGPYRO_FACES_NEEDING_BCS
IF (.NOT. ALLOCATED (NGPYRO_FACES_NEEDING_BCS) ) THEN 
   ALLOCATE(NGPYRO_FACES_NEEDING_BCS(0:GPG%NUM_GPYRO_MESHES))
   NGPYRO_FACES_NEEDING_BCS(:) = 0
ENDIF

!Set default gravity and position (then update for FDS)
G%GX = GPG%GX
G%GY = GPG%GY
G%GZ = GPG%GZ

IF (IGPYRO_TYPE .EQ. 2) THEN !FDS
   M%MESH_CENTROIDS(1:3) = GPG%MESH_CENTROIDS (IMESH,1:3)
   M%MESH_EXTENTS  (1:3) = GPG%MESH_EXTENTS   (IMESH,1:3)

   M%MESH_LL(1:3) = M%MESH_CENTROIDS(1:3) - 0.5D0 * M%MESH_EXTENTS(1:3)
   
   !Set x0, y0, z0:
   M%X0 = M%MESH_LL(1)
   M%Y0 = M%MESH_LL(2)
   M%Z0 = M%MESH_LL(3)
ELSE
   !Set x0, y0, z0:
   M%X0 = 0D0
   M%Y0 = 0D0
   M%Z0 = 0D0
ENDIF

NCELLZ = M%NCELLZ
NCELLX = M%NCELLX
NCELLY = M%NCELLY

NGSPEC = GPROP%NGSPEC
NSSPEC = SPROP%NSSPEC
NRXN   = SPROP%NRXN
NHGRXN = GPROP%NHGRXN

!For extension to 3D, consolidate all directional (x,y,z) quantities here:

ALLOCATE (G%FT(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%FT=0D0
ALLOCATE (G%FB(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%FB=0D0
ALLOCATE (G%FE(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%FE=0D0
ALLOCATE (G%FW(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%FW=0D0
ALLOCATE (G%FN(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%FN=0D0
ALLOCATE (G%FS(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%FS=0D0

ALLOCATE(G%NEEDSBCT(1:NCELLZ,1:NCELLX,1:NCELLY)); G%NEEDSBCT(:,:,:) = .FALSE.
ALLOCATE(G%NEEDSBCB(1:NCELLZ,1:NCELLX,1:NCELLY)); G%NEEDSBCB(:,:,:) = .FALSE.
ALLOCATE(G%NEEDSBCW(1:NCELLZ,1:NCELLX,1:NCELLY)); G%NEEDSBCW(:,:,:) = .FALSE.
ALLOCATE(G%NEEDSBCE(1:NCELLZ,1:NCELLX,1:NCELLY)); G%NEEDSBCE(:,:,:) = .FALSE.
ALLOCATE(G%NEEDSBCS(1:NCELLZ,1:NCELLX,1:NCELLY)); G%NEEDSBCS(:,:,:) = .FALSE.
ALLOCATE(G%NEEDSBCN(1:NCELLZ,1:NCELLX,1:NCELLY)); G%NEEDSBCN(:,:,:) = .FALSE.


CALL ALLOCATE_MEMORY_FOR_FIELD(IMESH, NCELLZ, NCELLX, NCELLY, NSSPEC, NGSPEC)
CALL ASSIGN_FIELD_TO_MEMORY

ALLOCATE (G%KZ    (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KZ=0D0
ALLOCATE (G%KX    (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KX=0D0
ALLOCATE (G%KY    (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KY=0D0


!k/c in x, y, and z directions:
ALLOCATE (G%KOCT  (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCT=0D0 !k/c (top)
ALLOCATE (G%KOCB  (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCB=0D0 !k/c (bottom)
ALLOCATE (G%KOCE  (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCE=0D0 !k/c (east)
ALLOCATE (G%KOCW  (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCW=0D0 !k/c (west)
ALLOCATE (G%KOCN  (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCN=0D0 !k/c (north)
ALLOCATE (G%KOCS  (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCS=0D0 !k/c (south)

ALLOCATE (G%KAPPA(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KAPPA=0D0 
ALLOCATE(G%RESIDUAL_TMP(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RESIDUAL_TMP = 0D0 

IF (GPG%SOLVE_PRESSURE) THEN 
   ALLOCATE(G%RESIDUAL_P(1:NCELLZ,1:NCELLX,1:NCELLY))
   G%RESIDUAL_P = 0D0 
ENDIF

IF (GPG%SOLVE_GAS_ENERGY) THEN 
   ALLOCATE(G%RESIDUAL_HG(1:NCELLZ,1:NCELLX,1:NCELLY))
   G%RESIDUAL_HG = 0D0 
ENDIF

IF (NSSPEC .GT. 0) THEN 
   ALLOCATE(G%RESIDUAL_YIS(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY))
   G%RESIDUAL_YIS = 0D0 
ENDIF

IF (GPG%SOLVE_GAS_YJ) THEN 
   ALLOCATE(G%RESIDUAL_YJG(1:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY))
   G%RESIDUAL_YJG = 0D0 
ENDIF

IF (GPG%SHYI_CORRECTION) THEN
   ALLOCATE (G%KOCHIT  (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCHIT=0D0 !(k/c) * hi (top)
   ALLOCATE (G%KOCHIB  (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCHIB=0D0 !(k/c) * hi (bottom) 
   ALLOCATE (G%KOCHIE  (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCHIE=0D0 !(k/c) * hi (east)
   ALLOCATE (G%KOCHIW  (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCHIW=0D0 !(k/c) * hi (west)
   ALLOCATE (G%KOCHIN  (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCHIN=0D0 !(k/c) * hi (north)
   ALLOCATE (G%KOCHIS  (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%KOCHIS=0D0 !(k/c) * hi (south)

   ALLOCATE (G%SHYI     (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%SHYI     =0D0

ENDIF

IF (GPG%SOLVE_PRESSURE) THEN
   ALLOCATE (G%BUOYANCYZ(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%BUOYANCYZ=0D0
   ALLOCATE (G%BUOYANCYX(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%BUOYANCYX=0D0
   ALLOCATE (G%BUOYANCYY(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%BUOYANCYY=0D0

   ALLOCATE (G%PERMZ      (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMZ=0D0
   ALLOCATE (G%PERMX      (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMX=0D0
   ALLOCATE (G%PERMY      (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMY=0D0

   ALLOCATE (G%PERMONUT   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMONUT=0D0
   ALLOCATE (G%PERMONUB   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMONUB=0D0
   ALLOCATE (G%PERMONUE   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMONUE=0D0
   ALLOCATE (G%PERMONUW   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMONUW=0D0
   ALLOCATE (G%PERMONUN   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMONUN=0D0
   ALLOCATE (G%PERMONUS   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PERMONUS=0D0

   ALLOCATE (G%MDOTPPDARCYT(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPDARCYT=0D0
   ALLOCATE (G%MDOTPPDARCYB(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPDARCYB=0D0
   ALLOCATE (G%MDOTPPDARCYE(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPDARCYE=0D0
   ALLOCATE (G%MDOTPPDARCYW(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPDARCYW=0D0
   ALLOCATE (G%MDOTPPDARCYN(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPDARCYN=0D0
   ALLOCATE (G%MDOTPPDARCYS(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPDARCYS=0D0
ENDIF

ALLOCATE (G%INDICE_OF_BC_GAS_OUT(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%INDICE_OF_BC_GAS_OUT=0D0

!z-direction mass flux, calculated from continuity:
ALLOCATE (G%MDOTPPZ(0:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPZ=0D0
ALLOCATE (G%MDOTPPZT(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPZT=0D0 ! Mass Flux z Top
ALLOCATE (G%MDOTPPZB(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%MDOTPPZB=0D0 ! Mass Flux z Bottom

IF (GPG%SOLVE_GAS_YJ .OR. GPG%SOLVE_PRESSURE) THEN
   ALLOCATE (G%PSIRGDT(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PSIRGDT=0D0
   ALLOCATE (G%PSIRGDB(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PSIRGDB=0D0
   ALLOCATE (G%PSIRGDE(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PSIRGDE=0D0
   ALLOCATE (G%PSIRGDW(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PSIRGDW=0D0
   ALLOCATE (G%PSIRGDN(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PSIRGDN=0D0
   ALLOCATE (G%PSIRGDS(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%PSIRGDS=0D0

   ALLOCATE (G%RGNT(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RGNT=0D0
   ALLOCATE (G%RGNB(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RGNB=0D0
   ALLOCATE (G%RGNE(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RGNE=0D0
   ALLOCATE (G%RGNW(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RGNW=0D0
   ALLOCATE (G%RGNN(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RGNN=0D0
   ALLOCATE (G%RGNS(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RGNS=0D0
ENDIF

!End of directional quantities

!Now allocate major variables:

ALLOCATE (G%CPS   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%CPS=1D0
ALLOCATE (G%SHP   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%SHP=0D0
ALLOCATE (G%SHM   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%SHM=0D0
ALLOCATE (G%SHNET (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%SHNET=0D0

ALLOCATE (G%OMEGASFG(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%OMEGASFG=0D0
   
ALLOCATE (G%OMSOLIDFRAC(1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%OMSOLIDFRAC=0D0

ALLOCATE (G%HI      (1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%HI=0D0
ALLOCATE (G%INITIAL_MASS  (0:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%INITIAL_MASS=0D0
   
ALLOCATE (G%UNREACTEDNESS(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%UNREACTEDNESS=1D0
            
ALLOCATE (G%OMEGASFBK  (1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%OMEGASFBK=0D0
ALLOCATE (G%OMEGASDAK  (1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%OMEGASDAK=0D0
ALLOCATE (G%OMEGASFGK  (1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%OMEGASFGK=0D0
            
ALLOCATE (G%RRT(1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RRT=0D0
ALLOCATE (G%RRY(1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RRY=0D0

ALLOCATE (G%SOMEGA   (1:3,1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%SOMEGA=0D0
ALLOCATE (G%GOMEGA   (1:3,0:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%GOMEGA=0D0
ALLOCATE (G%OMEGASFJK(1:NGSPEC,1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY)); G%OMEGASFJK=0D0
ALLOCATE (G%OMEGASDJK(1:NGSPEC,1:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY)); G%OMEGASDJK=0D0

ALLOCATE (G%IS_REACTING(0:NRXN,1:NCELLZ,1:NCELLX,1:NCELLY));G%IS_REACTING=.FALSE.


ALLOCATE (G%OMEGAGDJL(1:NGSPEC,1:NHGRXN,1:NCELLZ,1:NCELLX,1:NCELLY)); G%OMEGAGDJL=0D0
                        
ALLOCATE (G%QSG       (1:NCELLZ,1:NCELLX,1:NCELLY));G%QSG=0D0
ALLOCATE (G%QSC       (1:NCELLZ,1:NCELLX,1:NCELLY));G%QSC=0D0
ALLOCATE (G%QSBC      (1:NCELLZ,1:NCELLX,1:NCELLY));G%QSBC=0D0
ALLOCATE (G%CONSUMED  (1:NCELLZ,1:NCELLX,1:NCELLY));G%CONSUMED=.FALSE.

IF (GPG%SOLVE_GAS_ENERGY) THEN
   ALLOCATE (G%SHGP   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%SHGP=0D0
   ALLOCATE (G%SHGM   (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%SHGM=0D0
   ALLOCATE (G%HGRR   (1:NHGRXN,1:NCELLZ,1:NCELLX,1:NCELLY)); G%HGRR=0D0
   IF (GPROP%NHGRXN .GT. 0) THEN
      ALLOCATE (G%HGOMEGA(1:3,0:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY))
      G%HGOMEGA=0D0
   ENDIF
ENDIF

            
IF (GPG%SOLVE_PRESSURE .OR. GPG%SOLVE_GAS_YJ) THEN
   ALLOCATE (G%D12(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%D12=0D0
ENDIF
            

IF ( (.NOT. GPG%THERMAL_EQUILIBRIUM) .AND. GPG%HCV .LT. 0D0) THEN 
   ALLOCATE(G%HCV(1:NCELLZ,1:NCELLX,1:NCELLY) ); G%HCV=0D0
   ALLOCATE(G%RE (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%RE=0D0
   ALLOCATE(G%NU (1:NCELLZ,1:NCELLX,1:NCELLY) ); G%NU=0D0
ENDIF

ALLOCATE (G%THICKNESS (1:NCELLX,1:NCELLY) ); G%THICKNESS = 0D0

! If this is a TGA experiment...
IF (NCELLZ .EQ. 1 .AND. (.NOT. GPG%NEED_GAS_YJ) ) THEN
   ALLOCATE (G%YJG     (1:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%YJG=0D0
   ALLOCATE (G%YJGN    (1:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY) ); G%YJGN=0D0
ENDIF

ALLOCATE(G%RWORK01(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK01=0D0
ALLOCATE(G%RWORK02(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK02=0D0
ALLOCATE(G%RWORK03(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK03=0D0
ALLOCATE(G%RWORK04(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK04=0D0
ALLOCATE(G%RWORK05(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK05=0D0
ALLOCATE(G%RWORK06(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK06=0D0
ALLOCATE(G%RWORK07(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK07=0D0
ALLOCATE(G%RWORK08(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK08=0D0
ALLOCATE(G%RWORK09(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK09=0D0
ALLOCATE(G%RWORK10(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK10=0D0
ALLOCATE(G%RWORK11(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK11=0D0
ALLOCATE(G%RWORK12(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK12=0D0
ALLOCATE(G%RWORK13(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK13=0D0
ALLOCATE(G%RWORK14(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK14=0D0
ALLOCATE(G%RWORK15(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK15=0D0
ALLOCATE(G%RWORK16(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK16=0D0
ALLOCATE(G%RWORK17(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK17=0D0
ALLOCATE(G%RWORK18(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK18=0D0
ALLOCATE(G%RWORK19(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK19=0D0
ALLOCATE(G%RWORK20(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK20=0D0
ALLOCATE(G%RWORK21(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK21=0D0
ALLOCATE(G%RWORK22(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK22=0D0
ALLOCATE(G%RWORK23(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK23=0D0
ALLOCATE(G%RWORK24(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK24=0D0
ALLOCATE(G%RWORK25(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK25=0D0
ALLOCATE(G%RWORK26(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK26=0D0
ALLOCATE(G%RWORK27(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK27=0D0
ALLOCATE(G%RWORK28(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK28=0D0
ALLOCATE(G%RWORK29(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK29=0D0
ALLOCATE(G%RWORK30(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK30=0D0
ALLOCATE(G%RWORK31(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK31=0D0
ALLOCATE(G%RWORK32(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK32=0D0
ALLOCATE(G%RWORK33(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK33=0D0
ALLOCATE(G%RWORK34(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK34=0D0
ALLOCATE(G%RWORK35(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK35=0D0
ALLOCATE(G%RWORK36(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK36=0D0
ALLOCATE(G%RWORK37(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK37=0D0
ALLOCATE(G%RWORK38(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK38=0D0
ALLOCATE(G%RWORK39(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK39=0D0
ALLOCATE(G%RWORK40(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK40=0D0
ALLOCATE(G%RWORK41(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK41=0D0
ALLOCATE(G%RWORK42(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK42=0D0
ALLOCATE(G%RWORK43(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK43=0D0
ALLOCATE(G%RWORK44(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK44=0D0
ALLOCATE(G%RWORK45(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK45=0D0
ALLOCATE(G%RWORK46(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK46=0D0
ALLOCATE(G%RWORK47(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK47=0D0
ALLOCATE(G%RWORK48(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK48=0D0
ALLOCATE(G%RWORK49(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK49=0D0
ALLOCATE(G%RWORK50(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK50=0D0
ALLOCATE(G%RWORK51(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK51=0D0
ALLOCATE(G%RWORK52(1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK52=0D0

ALLOCATE(G%RWORK100(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK100=0D0
ALLOCATE(G%RWORK101(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK101=0D0
ALLOCATE(G%RWORK102(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK102=0D0
ALLOCATE(G%RWORK103(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK103=0D0
ALLOCATE(G%RWORK104(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK104=0D0
ALLOCATE(G%RWORK105(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK105=0D0
ALLOCATE(G%RWORK106(1:NSSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK106=0D0

ALLOCATE(G%RWORK110(1:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK110=0D0
ALLOCATE(G%RWORK111(1:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK111=0D0
ALLOCATE(G%RWORK112(1:NGSPEC,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK112=0D0

ALLOCATE(G%RWORK120(1:SPROP%NRXN,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK120=0D0
ALLOCATE(G%RWORK121(1:SPROP%NRXN,1:NCELLZ,1:NCELLX,1:NCELLY)); G%RWORK121=0D0

ALLOCATE(G%LWORK01(1:NCELLZ,1:NCELLX,1:NCELLY)); G%LWORK01=.FALSE.

ALLOCATE(G%WORK_DUMP(GPG%N_PROFILE_QUANTITIES))
DO I = 1, GPG%N_PROFILE_QUANTITIES
   STR_SIZE= MAX(NCELLX,NCELLY,NCELLZ)+1
   ALLOCATE(G%WORK_DUMP(I)%BUFFER(STR_SIZE))
   ALLOCATE(CHARACTER(STR_SIZE * 20) :: G%WORK_DUMP(I)%LINE)
ENDDO


ALLOCATE(G%CONV_INFO%CONVERGED_YIS(0:NSSPEC))
ALLOCATE(G%CONV_INFO%CONVERGED_YJG(0:NGSPEC))
ALLOCATE(G%CONV_INFO%ITER_YIS(0:NSSPEC))
ALLOCATE(G%CONV_INFO%ITER_YJG(0:NGSPEC))

!******************************************************************************
END SUBROUTINE ALLOCATE_GPYRO
!******************************************************************************

!******************************************************************************
SUBROUTINE ALLOCATE_GPYRO_BOUNDARYS_INFO(NMESHES,IMESH,IDIM)
!******************************************************************************

INTEGER, INTENT(IN) :: NMESHES, IMESH, IDIM
INTEGER :: ICOUNT !, LUSIZE
TYPE (GPYRO_BOUNDARYS_INFORMATION), POINTER :: BOUNDARYS

IF (.NOT. ALLOCATED(GP_BOUDARYS)) ALLOCATE (GP_BOUDARYS(0:NMESHES))

BOUNDARYS => GP_BOUDARYS(IMESH)

ALLOCATE (BOUNDARYS%IMESH_GPYRO(1:IDIM)); BOUNDARYS%IMESH_GPYRO(:) = 0
ALLOCATE (BOUNDARYS%IZ_GPYRO   (1:IDIM)); BOUNDARYS%IZ_GPYRO   (:) = 0
ALLOCATE (BOUNDARYS%IX_GPYRO   (1:IDIM)); BOUNDARYS%IX_GPYRO   (:) = 0
ALLOCATE (BOUNDARYS%IY_GPYRO   (1:IDIM)); BOUNDARYS%IY_GPYRO   (:) = 0
ALLOCATE (BOUNDARYS%IOR_GPYRO  (1:IDIM)); BOUNDARYS%IOR_GPYRO  (:) = 0
ALLOCATE (BOUNDARYS%SURF_IDX   (1:IDIM)); BOUNDARYS%SURF_IDX   (:) = -1
ALLOCATE (BOUNDARYS%IOR_FDS    (1:IDIM)); BOUNDARYS%IOR_FDS    (:) = 0
ALLOCATE (BOUNDARYS%IMESH_FDS  (1:IDIM)); BOUNDARYS%IMESH_FDS  (:) = 0
ALLOCATE (BOUNDARYS%I_FDS      (1:IDIM)); BOUNDARYS%I_FDS      (:) = 0
ALLOCATE (BOUNDARYS%J_FDS      (1:IDIM)); BOUNDARYS%J_FDS      (:) = 0
ALLOCATE (BOUNDARYS%K_FDS      (1:IDIM)); BOUNDARYS%K_FDS      (:) = 0
ALLOCATE (BOUNDARYS%IW_FDS     (1:IDIM)); BOUNDARYS%IW_FDS     (:) = 0
ALLOCATE (BOUNDARYS%RATIO      (1:IDIM)); BOUNDARYS%RATIO      (:) = 0
ALLOCATE (BOUNDARYS%DIFF       (1:IDIM)); BOUNDARYS%DIFF       (:) = 9D9
ALLOCATE (BOUNDARYS%XDIFF      (1:IDIM)); BOUNDARYS%XDIFF      (:) = 9D9
ALLOCATE (BOUNDARYS%YDIFF      (1:IDIM)); BOUNDARYS%YDIFF      (:) = 9D9
ALLOCATE (BOUNDARYS%ZDIFF      (1:IDIM)); BOUNDARYS%ZDIFF      (:) = 9D9
ALLOCATE (BOUNDARYS%Z_GPYRO    (1:IDIM)); BOUNDARYS%Z_GPYRO    (:) = 0D0
ALLOCATE (BOUNDARYS%X_GPYRO    (1:IDIM)); BOUNDARYS%X_GPYRO    (:) = 0D0
ALLOCATE (BOUNDARYS%Y_GPYRO    (1:IDIM)); BOUNDARYS%Y_GPYRO    (:) = 0D0
ALLOCATE (BOUNDARYS%X_FDS      (1:IDIM)); BOUNDARYS%X_FDS      (:) = 0D0
ALLOCATE (BOUNDARYS%Y_FDS      (1:IDIM)); BOUNDARYS%Y_FDS      (:) = 0D0
ALLOCATE (BOUNDARYS%Z_FDS      (1:IDIM)); BOUNDARYS%Z_FDS      (:) = 0D0
ALLOCATE (BOUNDARYS%COMPLETE_CELL_AT_BC(1:IDIM)); BOUNDARYS%COMPLETE_CELL_AT_BC(:) = .FALSE.
ALLOCATE (BOUNDARYS%GPBC       (1:IDIM))



DO ICOUNT = 1, IDIM
   BOUNDARYS%GPBC(ICOUNT)%QE            = 0D0
   BOUNDARYS%GPBC(ICOUNT)%QENET         = 0D0
   BOUNDARYS%GPBC(ICOUNT)%HC0           = 0D0
   BOUNDARYS%GPBC(ICOUNT)%TINF          = 0D0
   BOUNDARYS%GPBC(ICOUNT)%TFIXED        = 0D0
   BOUNDARYS%GPBC(ICOUNT)%HFIXED        = 0D0
   BOUNDARYS%GPBC(ICOUNT)%PRES          = 0D0
   BOUNDARYS%GPBC(ICOUNT)%MFLUX         = 0D0
   BOUNDARYS%GPBC(ICOUNT)%HM0           = 0D0
   BOUNDARYS%GPBC(ICOUNT)%QEG           = 0D0
   BOUNDARYS%GPBC(ICOUNT)%HC0G          = 0D0
   BOUNDARYS%GPBC(ICOUNT)%TINFG         = 0D0
   BOUNDARYS%GPBC(ICOUNT)%TFIXEDG       = 0D0
   BOUNDARYS%GPBC(ICOUNT)%HFIXEDG       = 0D0
   BOUNDARYS%GPBC(ICOUNT)%RERAD         = .FALSE.
   BOUNDARYS%GPBC(ICOUNT)%EMISSIVITY    = 0D0
   BOUNDARYS%GPBC(ICOUNT)%T_SURFACE     = 0D0
   BOUNDARYS%GPBC(ICOUNT)%T_SURFACE_OLD = 0D0
   BOUNDARYS%GPBC(ICOUNT)%QRADOUT       = 0D0
   BOUNDARYS%GPBC(ICOUNT)%QCONF         = 0D0
   ALLOCATE(BOUNDARYS%GPBC(ICOUNT)%YJINF   (1:GPROP%NGSPEC)); BOUNDARYS%GPBC(ICOUNT)%YJINF   (:) = 0D0
   ALLOCATE(BOUNDARYS%GPBC(ICOUNT)%MASSFLUX(1:GPROP%NGSPEC)); BOUNDARYS%GPBC(ICOUNT)%MASSFLUX(:) = 0D0
   ALLOCATE(BOUNDARYS%GPBC(ICOUNT)%MLR     (1:GPROP%NGSPEC)); BOUNDARYS%GPBC(ICOUNT)%MLR     (:) = 0D0
ENDDO

!******************************************************************************
END SUBROUTINE ALLOCATE_GPYRO_BOUNDARYS_INFO
!******************************************************************************


! *****************************************************************************
SUBROUTINE ALLOCATE_MESH(IMESH)
! *****************************************************************************
INTEGER, INTENT(IN) :: IMESH
TYPE(GPYRO_MESH_TYPE), POINTER :: M
INTEGER ::NCELLZ,NCELLX,NCELLY
M => G%MESH

M%ZDIM = GPG%ZDIM(IMESH); IF (M%NCELLZ .EQ. 1) M%ZDIM = 1.
M%XDIM = GPG%XDIM(IMESH); IF (M%NCELLX .EQ. 1) M%XDIM = 1.
M%YDIM = GPG%YDIM(IMESH); IF (M%NCELLY .EQ. 1) M%YDIM = 1.

M%NCELLZ = GPG%NCELLZ(IMESH)
M%NCELLX = GPG%NCELLX(IMESH)
M%NCELLY = GPG%NCELLY(IMESH)

M%DIMENSION = 0
IF (M%NCELLZ .GT.1 ) M%DIMENSION = M%DIMENSION +1
IF (M%NCELLX .GT.1 ) M%DIMENSION = M%DIMENSION +1
IF (M%NCELLY .GT.1 ) M%DIMENSION = M%DIMENSION +1


M%HALF_CELLS_AT_BC = GPG%HALF_CELLS_AT_BC(IMESH)
IF (.NOT. M%HALF_CELLS_AT_BC ) THEN
   ! If the cell at the boundary is a complete cell, add 2 ghost cells at the edge.
   IF (M%NCELLZ .NE. 1) M%NCELLZ = M%NCELLZ +2
   IF (M%NCELLX .NE. 1) M%NCELLX = M%NCELLX +2
   IF (M%NCELLY .NE. 1) M%NCELLY = M%NCELLY +2
ENDIF

NCELLZ=M%NCELLZ
NCELLX=M%NCELLX
NCELLY=M%NCELLY

!SOLVER_DEFORMATION_MODE : 1 No deformation
!                        : 2 Deformation But Flux computed as the initial non deformed mesh
!                        : 3 Deformation And Heat Flux acount for mesh distortient 

IF (GPG%SOLVER_DEFORMATION_MODE .EQ. 1) M%DEFORMATION = .TRUE.
IF (GPG%SOLVER_DEFORMATION_MODE .GT. 1) M%DEFORMATION = .FALSE.


!Coordinates of cell center in z, x, and y directions:
ALLOCATE (M%Z(1:NCELLZ,1:NCELLX,1:NCELLY)); M%Z=0D0
ALLOCATE (M%X(1:NCELLX) ); M%X=0D0
ALLOCATE (M%Y(1:NCELLY) ); M%Y=0D0

ALLOCATE(M%IMASK  (1:NCELLZ,1:NCELLX,1:NCELLY)); M%IMASK= .FALSE.
ALLOCATE(M%ID_OBST(1:NCELLZ,1:NCELLX,1:NCELLY)); M%ID_OBST(:,:,:) = 0

!Distance between cell centers in z, x, and y directions
ALLOCATE (M%DZT  (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DZT=9D9 !Delta-z (top)
ALLOCATE (M%DZB  (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DZB=9D9 !Delta-z (bottom)
ALLOCATE (M%DXE  (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DXE=9D9 !Delta-x (east)
ALLOCATE (M%DXW  (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DXW=9D9 !Delta-x (west)
ALLOCATE (M%DYN  (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DYN=9D9 !Delta-y (north)
ALLOCATE (M%DYS  (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DYS=9D9 !Delta-y (south)


ALLOCATE (M%DZ    (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DZ = 0D0 ! Cell size in z direction
ALLOCATE (M%DZN   (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DZN= 0D0 ! Delta-z at the new time step
ALLOCATE (M%DX    (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DX = 0D0 ! Cell size in x direction
ALLOCATE (M%DY    (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DY = 0D0 ! Cell size in y direction

ALLOCATE (M%DV    (1:NCELLZ,1:NCELLX,1:NCELLY) ); M%DV = 0D0 ! Cell volume 

! Surface area of the cell
ALLOCATE (M%SXE  (1:NCELLZ,1:NCELLX,1:NCELLY)); M%SXE = 0D0 ! East direction
ALLOCATE (M%SXW  (1:NCELLZ,1:NCELLX,1:NCELLY)); M%SXW = 0D0 ! West direction
ALLOCATE (M%SYN  (1:NCELLZ,1:NCELLX,1:NCELLY)); M%SYN = 0D0 ! North direction
ALLOCATE (M%SYS  (1:NCELLZ,1:NCELLX,1:NCELLY)); M%SYS = 0D0 ! South direction
ALLOCATE (M%DXDY (1:NCELLZ,1:NCELLX,1:NCELLY)); M%DXDY= 0D0 ! Dx * Dy (z-direction)

!Geometric coefficient introduced for diffusive solvers
ALLOCATE (M%GZT (1:NCELLZ,1:NCELLX,1:NCELLY)); M%GZT = 0D0
ALLOCATE (M%GZB (1:NCELLZ,1:NCELLX,1:NCELLY)); M%GZB = 0D0
ALLOCATE (M%GXE (1:NCELLZ,1:NCELLX,1:NCELLY)); M%GXE = 0D0
ALLOCATE (M%GXW (1:NCELLZ,1:NCELLX,1:NCELLY)); M%GXW = 0D0
ALLOCATE (M%GYN (1:NCELLZ,1:NCELLX,1:NCELLY)); M%GYN = 0D0
ALLOCATE (M%GYS (1:NCELLZ,1:NCELLX,1:NCELLY)); M%GYS = 0D0


IF (GPG%SOLVER_DEFORMATION_MODE .GE. 3) THEN
   ALLOCATE (M%TAN_ZX (1:NCELLZ+1,1:NCELLX,1:NCELLY)); M%TAN_ZX = 9D9
   ALLOCATE (M%TAN_ZY (1:NCELLZ+1,1:NCELLX,1:NCELLY)); M%TAN_ZY = 9D9
   ALLOCATE (M%TAN_X  (1:NCELLZ,1:NCELLX+1,1:NCELLY)); M%TAN_X  = 9D9
   ALLOCATE (M%TAN_Y  (1:NCELLZ,1:NCELLX,1:NCELLY+1)); M%TAN_Y  = 9D9
ENDIF

! *****************************************************************************
END SUBROUTINE ALLOCATE_MESH
! *****************************************************************************

! *****************************************************************************
SUBROUTINE ALLOCATE_MEMORY_FOR_FIELD(IMESH, NCELLZ, NCELLX, NCELLY, NSSPEC, NGSPEC)
! *****************************************************************************
INTEGER, INTENT(IN) :: IMESH, NCELLZ, NCELLX, NCELLY
INTEGER, INTENT(IN) :: NSSPEC, NGSPEC
TYPE( GPYRO_DOMAIN_TYPE), POINTER :: G
TYPE(GPYRO_STORAGE_TYPE), POINTER :: S

G => GPM(IMESH)
S => G%STORAGE

! Arrays 3D (NCELLZ, NCELLX, NCELLY)
ALLOCATE(S%TP_W1(NCELLZ,NCELLX,NCELLY),     S%TP_W2(NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%HP_W1(NCELLZ,NCELLX,NCELLY),     S%HP_W2(NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%RP_W1(NCELLZ,NCELLX,NCELLY),     S%RP_W2(NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%DZ_W1(NCELLZ,NCELLX,NCELLY),     S%DZ_W2(NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%MASS_W1(NCELLZ,NCELLX,NCELLY),   S%MASS_W2(NCELLZ,NCELLX,NCELLY))

IF (GPG%SOLVE_GAS_YJ .OR. GPG%SOLVE_PRESSURE) THEN
   ALLOCATE(S%RG_W1(NCELLZ,NCELLX,NCELLY),     S%RG_W2(NCELLZ,NCELLX,NCELLY))
ENDIF
IF (GPG%SOLVE_PRESSURE) THEN
   ALLOCATE(S%P_W1(NCELLZ,NCELLX,NCELLY),      S%P_W2(NCELLZ,NCELLX,NCELLY))
ENDIF

IF (GPG%SOLVE_GAS_ENERGY) THEN
   ALLOCATE(S%TG_W1(NCELLZ,NCELLX,NCELLY),     S%TG_W2(NCELLZ,NCELLX,NCELLY))
   ALLOCATE(S%HG_W1(NCELLZ,NCELLX,NCELLY),     S%HG_W2(NCELLZ,NCELLX,NCELLY))
ENDIF

IF (GPG%SOLVE_POROSITY) THEN
   ALLOCATE(S%RSP_W1(NCELLZ,NCELLX,NCELLY),    S%RSP_W2(NCELLZ,NCELLX,NCELLY))
   ALLOCATE(S%POROSS_W1(NCELLZ,NCELLX,NCELLY), S%POROSS_W2(NCELLZ,NCELLX,NCELLY))
ENDIF

! Arrays 4D (NSSPEC, NCELLZ, NCELLX, NCELLY)
ALLOCATE(S%YI_W1(NSSPEC,NCELLZ,NCELLX,NCELLY),       S%YI_W2(NSSPEC,NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%XI_W1(NSSPEC,NCELLZ,NCELLX,NCELLY),       S%XI_W2(NSSPEC,NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%MASS_I_W1(NSSPEC,NCELLZ,NCELLX,NCELLY),   S%MASS_I_W2(NSSPEC,NCELLZ,NCELLX,NCELLY))
ALLOCATE(S%TIME_INTEGRATED_MASS_PRODUCED_W1(NSSPEC,NCELLZ,NCELLX,NCELLY), S%TIME_INTEGRATED_MASS_PRODUCED_W2(NSSPEC,NCELLZ,NCELLX,NCELLY))

! Arrays 4D (NGSPEC, NCELLZ, NCELLX, NCELLY)
IF (GPG%NEED_GAS_YJ) THEN
   ALLOCATE(S%YJG_W1(NGSPEC,NCELLZ,NCELLX,NCELLY),      S%YJG_W2(NGSPEC,NCELLZ,NCELLX,NCELLY))
   ALLOCATE(S%M_W1(NCELLZ,NCELLX,NCELLY),      S%M_W2(NCELLZ,NCELLX,NCELLY))
ENDIF
! *****************************************************************************
END SUBROUTINE ALLOCATE_MEMORY_FOR_FIELD
! *****************************************************************************


! *****************************************************************************
SUBROUTINE ASSIGN_FIELD_TO_MEMORY
! *****************************************************************************
TYPE (GPYRO_MESH_TYPE), POINTER :: M

M => G%MESH

! Assign field pointers to their working memory (W1/W2)
G%TP    => G%STORAGE%TP_W1
G%TPN   => G%STORAGE%TP_W2

G%HP    => G%STORAGE%HP_W1
G%HPN   => G%STORAGE%HP_W2

G%RP    => G%STORAGE%RP_W1
G%RPN   => G%STORAGE%RP_W2

M%DZ  => G%STORAGE%DZ_W1
M%DZN => G%STORAGE%DZ_W2

G%MASS  => G%STORAGE%MASS_W1
G%MASS_N => G%STORAGE%MASS_W2


IF (GPG%SOLVE_GAS_YJ .OR. GPG%SOLVE_PRESSURE) THEN
   G%RG    => G%STORAGE%RG_W1
   G%RGN   => G%STORAGE%RG_W2
   G%M     => G%STORAGE%M_W1
   G%MN    => G%STORAGE%M_W2
ENDIF

IF (GPG%SOLVE_PRESSURE) THEN
   G%P     => G%STORAGE%P_W1
   G%PN    => G%STORAGE%P_W2
ENDIF

IF (GPG%SOLVE_GAS_ENERGY) THEN
   G%TG    => G%STORAGE%TG_W1
   G%TGN   => G%STORAGE%TG_W2
   G%HG    => G%STORAGE%HG_W1
   G%HGN   => G%STORAGE%HG_W2
ENDIF

IF (GPG%SOLVE_POROSITY) THEN
   G%RSP      => G%STORAGE%RSP_W1
   G%RSPN     => G%STORAGE%RSP_W2
   G%POROSS   => G%STORAGE%POROSS_W1
   G%POROSSN  => G%STORAGE%POROSS_W2
ENDIF

G%YI    => G%STORAGE%YI_W1
G%YIN   => G%STORAGE%YI_W2

G%XI    => G%STORAGE%XI_W1
G%XIN   => G%STORAGE%XI_W2

G%MASS_I  => G%STORAGE%MASS_I_W1
G%MASS_IN => G%STORAGE%MASS_I_W2

G%TIME_INTEGRATED_MASS_PRODUCED  => G%STORAGE%TIME_INTEGRATED_MASS_PRODUCED_W1
G%TIME_INTEGRATED_MASS_PRODUCEDN => G%STORAGE%TIME_INTEGRATED_MASS_PRODUCED_W2

IF (GPG%NEED_GAS_YJ) THEN
   G%YJG   => G%STORAGE%YJG_W1
   G%YJGN  => G%STORAGE%YJG_W2
ENDIF
! *****************************************************************************
END SUBROUTINE ASSIGN_FIELD_TO_MEMORY
! *****************************************************************************



!******************************************************************************
SUBROUTINE INIT_GPYRO(ICASE,IMESH)
!******************************************************************************

INTEGER, INTENT(IN) :: ICASE,IMESH


! This routine is called once for every mesh, so the following happens 
! multiple times but it's extremely fast so there is no reason to 
! add logic to only do it once:


CALL INIT_GPYRO_GENERAL(IMESH)

CALL INIT_REACTIONS


!========================================================!
!================== BUILD MESH AND IC ===================!
!========================================================!
! Initialise mesh
CALL INIT_MESH(IMESH)

CALL SETUP_DETAILED_ICS(IMESH)

! GP_BOUDARYS
CALL INIT_BOUNDARY_CELLS(IMESH)
!========================================================!
!========================================================!

CALL INIT_GPYRO_VARS(IMESH)

CALL INIT_DUMP_OUTPOUT(IMESH)

IF (IGPYRO_TYPE .EQ. 1 .AND. IMESH .EQ. 1) CALL WRITE_DOTOUT_FILE(ICASE,0D0,1) 

!******************************************************************************
END SUBROUTINE INIT_GPYRO
!******************************************************************************



!******************************************************************************
SUBROUTINE INIT_GPYRO_GENERAL(IMESH)
!******************************************************************************
INTEGER, INTENT(IN) :: IMESH

G=>GPM(IMESH)

! Alpha coefficients for relaxation:
IF (GPG%ALPHA .GT. 0D0 .AND. GPG%ALPHA .LE. 1D0) THEN
   GPG%ALPHA_YIS = GPG%ALPHA
   GPG%ALPHA_YJG = GPG%ALPHA
   GPG%ALPHA_HG  = GPG%ALPHA
   GPG%ALPHA_H   = GPG%ALPHA
   GPG%ALPHA_P   = GPG%ALPHA
ENDIF

GPG%TDATUM = 200D0

GPG%POSINF =  1. / TINY(0D0)
GPG%NEGINF = -1. / TINY(0D0)

GPG%TUSED(:) = 0D0 !Zero out CPU timing array

GPG%TDUMPLAST_GA           = 0D0
GPG%TDUMPLAST_POINT    (:) = 0D0
GPG%TDUMPLAST_PROFILE  (:) = 0D0
GPG%TDUMPLAST_SMOKEVIEW(:) = 0D0
GPG%TDUMPLAST_CSVDUMP  (:) = 0D0
GPG%DTNEXT                 = GPG%DT0

! Initialise time
G%NTIMESTEPS= 0
G%TLAST_TMP = 0D0
G%TLAST_YIS = 0D0
G%TLAST_YJG = 0D0
G%TLAST_P   = 0D0
G%TLAST_HG  = 0D0

!******************************************************************************
END SUBROUTINE INIT_GPYRO_GENERAL
!******************************************************************************


! *****************************************************************************
SUBROUTINE SETUP_DETAILED_ICS(IMESH)
! *****************************************************************************
INTEGER, INTENT(IN) :: IMESH
INTEGER :: IZ,IX,IY
INTEGER :: NCELLZ,NCELLX,NCELLY
INTEGER :: ICNUM, ID_OBST,ISPEC,IGSPEC
TYPE (GPYRO_MESH_TYPE), POINTER :: M
INTEGER :: SURF_IDX(1:6)

G => GPM(IMESH)
M => G%MESH

NCELLZ = M%NCELLZ
NCELLX = M%NCELLX
NCELLY = M%NCELLY


!$OMP PARALLEL DO SCHEDULE(STATIC) DEFAULT(SHARED) COLLAPSE(3)&
!$OMP PRIVATE(IZ,IX,IY,ID_OBST,ICNUM,ISPEC,IGSPEC)
DO IY = 1, NCELLY
DO IX = 1, NCELLX
DO IZ = 1, NCELLZ
   ID_OBST=M%ID_OBST(IZ,IX,IY)
   
   IF (ID_OBST .NE. 0) THEN
      ICNUM = GPG%GEOM(ID_OBST)%ICNUM
      SURF_IDX = GPG%GEOM(ID_OBST)%SURF_IDX
   ELSE ! Use Default mesh values
      ICNUM  = GPG%DEFAULT_IC(IMESH)
      SURF_IDX(1:6) = GPG%DEFAULT_SURF_IDX(IMESH,1:6)
   ENDIF
   
   G%TPN(IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%TMP_INITIAL
   G%TP (IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%TMP_INITIAL

   DO ISPEC = 1, SPROP%NSSPEC
      G%YIN(ISPEC,IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%YI0(ISPEC)
      G%YI (ISPEC,IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%YI0(ISPEC)
   ENDDO

   IF (GPG%NEED_GAS_YJ) THEN
      DO IGSPEC = 1, GPROP%NGSPEC
         G%YJGN(IGSPEC,IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%YJ0(IGSPEC)
         G%YJG (IGSPEC,IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%YJ0(IGSPEC)
      ENDDO
   ENDIF

   IF (GPG%SOLVE_PRESSURE) THEN
      G%PN (IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%P_INITIAL
      G%P  (IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%P_INITIAL
   ENDIF

   IF (GPG%SOLVE_GAS_ENERGY) THEN
      G%HGN(IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%TMPG_INITIAL
      G%HG (IZ,IX,IY) = GPG%INITIAL_CONDITIONS(ICNUM)%TMPG_INITIAL
   ENDIF
ENDDO
ENDDO
ENDDO
!$OMP END PARALLEL DO


! *****************************************************************************
END SUBROUTINE SETUP_DETAILED_ICS
! *****************************************************************************


!******************************************************************************
SUBROUTINE INIT_BOUNDARY_CELLS(IMESH)
!******************************************************************************

INTEGER, INTENT(IN) :: IMESH
INTEGER :: IZ,IX,IY,NCELLZ,NCELLX,NCELLY
INTEGER :: ICOUNT
TYPE (GPYRO_MESH_TYPE), POINTER :: M

G => GPM(IMESH)
M => G%MESH

NCELLZ = M%NCELLZ
NCELLX = M%NCELLX
NCELLY = M%NCELLY

IF (.NOT. M%HALF_CELLS_AT_BC) THEN
   ! Mask the Gost cells
   IF (NCELLZ .GT. 1) M%IMASK(1     ,:,:) = .TRUE.
   IF (NCELLZ .GT. 1) M%IMASK(NCELLZ,:,:) = .TRUE.
   IF (NCELLX .GT. 1) M%IMASK(:,1     ,:) = .TRUE.
   IF (NCELLX .GT. 1) M%IMASK(:,NCELLX,:) = .TRUE.
   IF (NCELLY .GT. 1) M%IMASK(:,:,1     ) = .TRUE.
   IF (NCELLY .GT. 1) M%IMASK(:,:,NCELLY) = .TRUE.
ENDIF

! Determine cells that need boundary conditions.

! First Count the number of Boundary Cells
ICOUNT = 0

!z-direction
DO IY = 1, NCELLY
DO IX = 1, NCELLX
DO IZ = 2, NCELLZ-1
   IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ-1,IX,IY))  ICOUNT = ICOUNT +1
   IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ+1,IX,IY))  ICOUNT = ICOUNT +1
ENDDO
ENDDO
ENDDO
!z-edges
DO IY = 1, NCELLY
DO IX = 1, NCELLX
   IZ=1     ; IF(.NOT. M%IMASK(IZ,IX,IY) ) ICOUNT = ICOUNT +1
   IZ=NCELLZ; IF(.NOT. M%IMASK(IZ,IX,IY) ) ICOUNT = ICOUNT +1
ENDDO
ENDDO

!x-direction
IF (NCELLX .GT. 1) THEN
   DO IY = 1, NCELLY
   DO IX = 2, NCELLX-1
   DO IZ = 1, NCELLZ
      IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX-1,IY)) ICOUNT = ICOUNT +1
      IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX+1,IY)) ICOUNT = ICOUNT +1
   ENDDO
   ENDDO
   ENDDO
   !x-edges
   DO IY = 1, NCELLY
   DO IZ = 1, NCELLZ
      IX=1     ; IF(.NOT. M%IMASK(IZ,IX,IY) ) ICOUNT = ICOUNT +1
      IX=NCELLX; IF(.NOT. M%IMASK(IZ,IX,IY) ) ICOUNT = ICOUNT +1
   ENDDO
   ENDDO
ENDIF

!y-direction
IF (NCELLY .GT. 1) THEN
   DO IY = 2, NCELLY-1
   DO IX = 1, NCELLX
   DO IZ = 1, NCELLZ
      IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX,IY-1)) ICOUNT = ICOUNT +1
      IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX,IY+1)) ICOUNT = ICOUNT +1
   ENDDO
   ENDDO
   ENDDO
   !y-edges
   DO IX = 1, NCELLX
   DO IZ = 1, NCELLZ
      IY=1     ; IF(.NOT. M%IMASK(IZ,IX,IY) ) ICOUNT = ICOUNT +1
      IY=NCELLY; IF(.NOT. M%IMASK(IZ,IX,IY) ) ICOUNT = ICOUNT +1
   ENDDO
   ENDDO
ENDIF

NGPYRO_FACES_NEEDING_BCS(IMESH) = ICOUNT

CALL ALLOCATE_GPYRO_BOUNDARYS_INFO(GPG%NUM_GPYRO_MESHES, IMESH, NGPYRO_FACES_NEEDING_BCS(IMESH))
ICOUNT=0

! Start with interior nodes:
!z-direction
DO IY = 1, NCELLY
DO IX = 1, NCELLX
DO IZ = 2, NCELLZ-1
   IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ-1,IX,IY))  CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY, 3,G%NEEDSBCT(IZ,IX,IY))
   IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ+1,IX,IY))  CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY,-3,G%NEEDSBCB(IZ,IX,IY))
ENDDO
ENDDO
ENDDO

!x-direction
IF (NCELLX .GT. 1) THEN
   DO IY = 1, NCELLY
   DO IX = 2, NCELLX-1
   DO IZ = 1, NCELLZ
      IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX-1,IY)) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY,-1,G%NEEDSBCW(IZ,IX,IY))
      IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX+1,IY)) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY, 1,G%NEEDSBCE(IZ,IX,IY))
   ENDDO
   ENDDO
   ENDDO
ENDIF

!y-direction
IF (NCELLY .GT. 1) THEN
DO IY = 2, NCELLY-1
DO IX = 1, NCELLX
DO IZ = 1, NCELLZ
   IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX,IY-1)) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY,-2,G%NEEDSBCS(IZ,IX,IY))
   IF ((.NOT. M%IMASK(IZ,IX,IY)) .AND. M%IMASK(IZ,IX,IY+1)) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY, 2,G%NEEDSBCN(IZ,IX,IY))
ENDDO
ENDDO
ENDDO
ENDIF

!Now do edges:
DO IY = 1, NCELLY
DO IX = 1, NCELLX
   IZ=1     ; IF(.NOT. M%IMASK(IZ,IX,IY) ) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY, 3,G%NEEDSBCT(IZ,IX,IY))
   IZ=NCELLZ; IF(.NOT. M%IMASK(IZ,IX,IY) ) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY,-3,G%NEEDSBCB(IZ,IX,IY))
ENDDO
ENDDO

IF (NCELLX .GT. 1) THEN
   DO IY = 1, NCELLY
   DO IZ = 1, NCELLZ
      IX=1     ; IF(.NOT. M%IMASK(IZ,IX,IY) ) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY,-1,G%NEEDSBCW(IZ,IX,IY))
      IX=NCELLX; IF(.NOT. M%IMASK(IZ,IX,IY) ) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY, 1,G%NEEDSBCE(IZ,IX,IY))
   ENDDO
   ENDDO
ENDIF

IF (NCELLY .GT. 1) THEN
   DO IX = 1, NCELLX
   DO IZ = 1, NCELLZ
      IY=1     ; IF(.NOT. M%IMASK(IZ,IX,IY) ) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY,-2,G%NEEDSBCS(IZ,IX,IY))
      IY=NCELLY; IF(.NOT. M%IMASK(IZ,IX,IY) ) CALL INIT_BOUNDARY(ICOUNT,IMESH,IZ,IX,IY, 2,G%NEEDSBCN(IZ,IX,IY))
   ENDDO
   ENDDO
ENDIF

! For each cell get the ID of the bounday cell were the gas will escape
CALL GET_EXIT_GAS_CELL(IMESH)
CONTAINS
! *****************************************************************************
SUBROUTINE INIT_BOUNDARY(ICOUNTP,IMESHP,IZP,IXP,IYP,IORP,NEEDSBC)
! *****************************************************************************
INTEGER, INTENT(INOUT) :: ICOUNTP
INTEGER, INTENT(IN) :: IMESHP, IZP, IXP, IYP, IORP
LOGICAL, INTENT(OUT) :: NEEDSBC
REAL(EB) :: ZGPYRO, XGPYRO, YGPYRO
LOGICAL :: COMPLETE_CELL_AT_BC
INTEGER :: ID_OBST, ICNUM
INTEGER :: SURF_IDX(1:6)
INTEGER :: ID_SURF

G => GPM(IMESHP)
ID_OBST = M%ID_OBST(IZP,IXP,IYP)

IF (ID_OBST .NE. 0) THEN
   SURF_IDX = GPG%GEOM(ID_OBST)%SURF_IDX
   ICNUM    = GPG%GEOM(ID_OBST)%ICNUM
ELSE ! Use Default mesh values
   SURF_IDX(1:6) = GPG%DEFAULT_SURF_IDX(IMESHP,1:6)
   ICNUM         = GPG%DEFAULT_IC(IMESHP)
ENDIF

SELECT CASE(IORP)
   CASE( 3) ; ID_SURF = SURF_IDX(5)   ! Top
   CASE(-3) ; ID_SURF = SURF_IDX(6)   ! Bottom
   CASE(-1) ; ID_SURF = SURF_IDX(1)   ! West
   CASE( 1) ; ID_SURF = SURF_IDX(2)   ! East
   CASE( 2) ; ID_SURF = SURF_IDX(4)   ! North
   CASE(-2) ; ID_SURF = SURF_IDX(3)   ! South
END SELECT


IF (ABS(IORP) .EQ. 1) THEN
   XGPYRO = M%X0 + M%X(IXP)
   ZGPYRO = M%Z0 + M%ZDIM - M%Z(IZP,IXP,IYP)
   YGPYRO = M%Y0 + M%Y(IYP)
   COMPLETE_CELL_AT_BC = .NOT. (IXP == 1 .OR. IXP == M%NCELLX)
ENDIF

IF (ABS(IORP) .EQ. 2) THEN
   YGPYRO = M%Y0 + M%Y(IYP)
   ZGPYRO = M%Z0 + M%ZDIM - M%Z(IZP,IXP,IYP)
   XGPYRO = M%X0 + M%X(IXP)
   COMPLETE_CELL_AT_BC = .NOT. (IYP == 1 .OR. IYP == M%NCELLY)
ENDIF

IF (ABS(IORP) .EQ. 3) THEN
   ZGPYRO = M%Z0 - M%Z(IZP,IXP,IYP) + M%ZDIM 
   YGPYRO = M%Y0 + M%Y(IYP)
   XGPYRO = M%X0 + M%X(IXP)
   COMPLETE_CELL_AT_BC = .NOT. (IZP == 1 .OR. IZP == NCELLZ)
ENDIF

ICOUNTP = ICOUNTP + 1
GP_BOUDARYS(IMESHP)%IMESH_GPYRO (ICOUNTP) = IMESHP
GP_BOUDARYS(IMESHP)%IZ_GPYRO    (ICOUNTP) = IZP
GP_BOUDARYS(IMESHP)%IX_GPYRO    (ICOUNTP) = IXP
GP_BOUDARYS(IMESHP)%IY_GPYRO    (ICOUNTP) = IYP
GP_BOUDARYS(IMESHP)%IOR_GPYRO   (ICOUNTP) = IORP
GP_BOUDARYS(IMESHP)%Z_GPYRO     (ICOUNTP) = ZGPYRO
GP_BOUDARYS(IMESHP)%X_GPYRO     (ICOUNTP) = XGPYRO
GP_BOUDARYS(IMESHP)%Y_GPYRO     (ICOUNTP) = YGPYRO
GP_BOUDARYS(IMESHP)%SURF_IDX    (ICOUNTP) = ID_SURF
GP_BOUDARYS(IMESHP)%COMPLETE_CELL_AT_BC(ICOUNTP)= COMPLETE_CELL_AT_BC

GP_BOUDARYS(IMESHP)%GPBC(ICOUNTP)%T_SURFACE_OLD = GPG%INITIAL_CONDITIONS(ICNUM)%TMP_INITIAL
GP_BOUDARYS(IMESHP)%GPBC(ICOUNTP)%T_SURFACE     = GPG%INITIAL_CONDITIONS(ICNUM)%TMP_INITIAL

NEEDSBC                      = .TRUE. 

! *****************************************************************************
END SUBROUTINE INIT_BOUNDARY
! *****************************************************************************

!******************************************************************************
END SUBROUTINE INIT_BOUNDARY_CELLS
!******************************************************************************



! *****************************************************************************
 SUBROUTINE INIT_GPYRO_VARS(IMESH)
! *****************************************************************************
INTEGER, INTENT(IN) :: IMESH

INTEGER :: NCELLZ, NCELLX, NCELLY, NSSPEC
INTEGER :: IZ, IX, IY, ISPEC
REAL(EB) :: HI, MWGN,RSUMYI
TYPE (GPYRO_MESH_TYPE), POINTER :: M

G => GPM(IMESH)
M => G%MESH

NCELLZ = M%NCELLZ
NCELLX = M%NCELLX
NCELLY = M%NCELLY
NSSPEC = SPROP%NSSPEC


! Calculate ambient density (only used if gravity is present)
IF (IGPYRO_TYPE .NE. 2 .AND. GPG%SOLVE_GAS_YJ) THEN !In FDS sim we set GPG%RHOINF = RHOA in main.f90
   MWGN = 0D0 
   DO ISPEC = 1, GPROP%NGSPEC
      MWGN = MWGN + GPG%INITIAL_CONDITIONS(GPG%DEFAULT_IC(IMESH))%YJ0(ISPEC) / GPROP%M(ISPEC)
   ENDDO
   MWGN = 1D0 / MWGN !Mean molecular weight
   GPG%RHOINF = GPG%P0 * MWGN / (8314D0 * GPG%TAMB)
ENDIF

DO IY = 1, NCELLY
DO IX = 1, NCELLX
DO IZ = 1, NCELLZ

   G%HP(IZ,IX,IY) = 0D0
   DO ISPEC = 1, NSSPEC
      HI = HOFT(ISPEC,G%TP(IZ,IX,IY) )
      G%HP(IZ,IX,IY) = G%HP(IZ,IX,IY) + G%YI(ISPEC,IZ,IX,IY)*HI
   ENDDO

   ! Calculate the weighted condensed-phase density and volume fractions
   RSUMYI  = 0D0 !For bulk density
   DO ISPEC = 1, NSSPEC
      IF (G%YIN(ISPEC,IZ,IX,IY) .EQ. 0) CYCLE
      RSUMYI = RSUMYI  + G%YIN(ISPEC,IZ,IX,IY)/RHOOFT(ISPEC,G%TP(IZ,IX,IY))
   ENDDO
   G%RP (IZ,IX,IY) = 1D0 / RSUMYI

   DO ISPEC = 1, NSSPEC
      G%XI(ISPEC,IZ,IX,IY) = G%RP(IZ,IX,IY)* G%YI(ISPEC,IZ,IX,IY) / RHOOFT(ISPEC,G%TP(IZ,IX,IY))
   ENDDO

   G%RPN (IZ,IX,IY)   = G%RP (IZ,IX,IY)
   G%XIN (:,IZ,IX,IY) = G%XI (:,IZ,IX,IY)

   ! Calculate MASS
   G%MASS  (IZ,IX,IY) = G%RP   (IZ,IX,IY) * M%DV(IZ,IX,IY)
   G%MASS_N(IZ,IX,IY) = G%MASS(IZ,IX,IY)

   ! Setup for TGA simulation
   IF (NCELLZ .EQ. 1) THEN
      M%DZ(IZ,IX,IY)   = 1D0/G%RP(IZ,IX,IY)
      M%DZN(IZ,IX,IY)  = M%DZ(IZ,IX,IY)
      G%MASS(IZ,IX,IY)  = G%RP(IZ,IX,IY) * M%DZ(IZ,IX,IY)
      G%MASS_N(IZ,IX,IY) = G%MASS(IZ,IX,IY)
      M%IMASK(IZ,IX,IY) = .FALSE.
   ENDIF

   ! Calculate mass of species i
   DO ISPEC = 1, NSSPEC
      G%MASS_I      (ISPEC,IZ,IX,IY) = G%MASS(IZ,IX,IY) * G%YI(ISPEC,IZ,IX,IY)
      G%INITIAL_MASS(ISPEC,IZ,IX,IY) = G%MASS_I(ISPEC,IZ,IX,IY)
      G%MASS_IN     (ISPEC,IZ,IX,IY) = G%MASS_I(ISPEC,IZ,IX,IY)
   ENDDO
   G%INITIAL_MASS(0,IZ,IX,IY) = G%MASS(IZ,IX,IY)

   ! Initialize TIME_INTEGRATED_MASS_PRODUCED (star)	     
   G%TIME_INTEGRATED_MASS_PRODUCED (:,IZ,IX,IY) = G%INITIAL_MASS(1:NSSPEC,IZ,IX,IY)
   G%TIME_INTEGRATED_MASS_PRODUCEDN(:,IZ,IX,IY) = G%INITIAL_MASS(1:NSSPEC,IZ,IX,IY)

   IF (GPG%CONVENTIONAL_RXN_ORDER) THEN
      DO ISPEC = 1, NSSPEC
         G%TIME_INTEGRATED_MASS_PRODUCED (ISPEC,IZ,IX,IY) = G%MASS(IZ,IX,IY)
         G%TIME_INTEGRATED_MASS_PRODUCEDN(ISPEC,IZ,IX,IY) = G%MASS(IZ,IX,IY)
      ENDDO
   ENDIF
         
   ! Set weighted thermal conductivity and specific heat
   G%CPS(IZ,IX,IY) = 0D0;  G%KZ (IZ,IX,IY) = 0D0
   DO ISPEC = 1, NSSPEC
      G%KZ (IZ,IX,IY) =  G%KZ (IZ,IX,IY)  + G%XI(ISPEC,IZ,IX,IY) * KZOFT(ISPEC,G%TP(IZ,IX,IY))
      G%CPS(IZ,IX,IY) =  G%CPS(IZ,IX,IY)  + G%YI(ISPEC,IZ,IX,IY) * CPOFT(ISPEC,G%TP(IZ,IX,IY))
      G%KAPPA(IZ,IX,IY)= G%KAPPA(IZ,IX,IY) +G%XI(ISPEC,IZ,IX,IY) * SPROP%KAPPA(ISPEC)
   ENDDO
 
   IF (NCELLX .GT. 1) THEN
      G%KX(IZ,IX,IY) = 0D0
      DO ISPEC = 1, NSSPEC
         G%KX(IZ,IX,IY) = G%KX(IZ,IX,IY) + G%XI(ISPEC,IZ,IX,IY) * KXOFT(ISPEC,G%TP(IZ,IX,IY))
      ENDDO
   ENDIF

   IF (NCELLY .GT. 1) THEN
      G%KY(IZ,IX,IY) = 0D0
      DO ISPEC = 1, NSSPEC
         G%KY(IZ,IX,IY) = G%KY(IZ,IX,IY) + G%XI(ISPEC,IZ,IX,IY) * KYOFT(ISPEC,G%TP(IZ,IX,IY))
      ENDDO
   ENDIF

   IF (GPG%SOLVE_GAS_YJ .OR. GPG%SOLVE_PRESSURE) THEN
      IF (GPG%SOLVE_GAS_YJ) THEN
         G%M(IZ,IX,IY)= 0D0
         DO ISPEC = 1, GPROP%NGSPEC
            G%M(IZ,IX,IY)= G%M(IZ,IX,IY) + G%YJG(ISPEC,IZ,IX,IY) * GPROP%M(ISPEC)
         ENDDO
         G%MN(IZ,IX,IY)= G%M(IZ,IX,IY)
      ELSE 
         G%M(IZ,IX,IY)= GPROP%M(1)
         G%MN(IZ,IX,IY)= G%M(IZ,IX,IY)
      ENDIF

      IF (GPG%SOLVE_PRESSURE) THEN
         DO ISPEC = 1, NSSPEC
            IF (NCELLZ .GT.0) G%PERMZ(IZ,IX,IY) = G%PERMZ(IZ,IX,IY) + G%XI(ISPEC,IZ,IX,IY)*SPROP%PERMZ(ISPEC)
            IF (NCELLX .GT.0) G%PERMX(IZ,IX,IY) = G%PERMX(IZ,IX,IY) + G%XI(ISPEC,IZ,IX,IY)*SPROP%PERMX(ISPEC)
            IF (NCELLY .GT.0) G%PERMY(IZ,IX,IY) = G%PERMY(IZ,IX,IY) + G%XI(ISPEC,IZ,IX,IY)*SPROP%PERMY(ISPEC)
         ENDDO
         !Set Hydrostatic pressure if gravity is present
         IF (G%GZ .NE. 0D0) G%P(IZ,IX,IY) = G%P(IZ,IX,IY) + GPG%RHOINF*G%GZ*M%Z(IZ,IX,IY)
         IF (G%GX .NE. 0D0) G%P(IZ,IX,IY) = G%P(IZ,IX,IY) + GPG%RHOINF*G%GX*M%X(IX)
         IF (G%GY .NE. 0D0) G%P(IZ,IX,IY) = G%P(IZ,IX,IY) + GPG%RHOINF*G%GY*M%Y(IY)
         G%PN (IZ,IX,IY) = G%P(IZ,IX,IY)

         G%RGN(IZ,IX,IY) = RHOGOFT(G%PN(IZ,IX,IY),G%M(IZ,IX,IY), G%TPN(IZ,IX,IY))
         G%RG (IZ,IX,IY) = G%RGN(IZ,IX,IY)
      ELSE
         G%RG (IZ,IX,IY) = RHOGOFT(GPG%P0, G%M(IZ,IX,IY), G%TPN(IZ,IX,IY))
         G%RGN(IZ,IX,IY) = G%RG(IZ,IX,IY)
      ENDIF

   ENDIF

   IF (GPG%SOLVE_GAS_ENERGY) THEN

      G%TG (IZ,IX,IY) = G%TP(IZ,IX,IY) !Gas temperature
      G%TGN(IZ,IX,IY) = G%TG(IZ,IX,IY) 

      G%HG (IZ,IX,IY) = GPROP%CPG * (G%TG(IZ,IX,IY)-GPG%TDATUM) !Gas enthalpy
      G%HGN(IZ,IX,IY) = G%HG(IZ,IX,IY)
   ENDIF


   IF (GPG%SOLVE_POROSITY) THEN
      RSUMYI = 0D0
      DO ISPEC = 1, NSSPEC
         RSUMYI = RSUMYI + G%YI(ISPEC,IZ,IX,IY) / SPROP%RS0(ISPEC)
      ENDDO
      G%RSP(IZ,IX,IY) = 1D0 / RSUMYI
      G%POROSS(IZ,IX,IY) = 1D0 - G%RP(IZ,IX,IY) / G%RSP(IZ,IX,IY)

      G%RSPN(IZ,IX,IY)    = G%RSP(IZ,IX,IY)
      G%POROSSN(IZ,IX,IY) = G%POROSS(IZ,IX,IY)
   ENDIF

ENDDO !IZ
ENDDO !IX
ENDDO !IY



!Record initial mass in mesh:
G%TOTAL_INITIAL_MASS = TOTAL_MASS(0)

GPG%MAXTMP = MAXVAL(G%TPN(:,:,:))
IF (GPG%SOLVE_GAS_ENERGY .AND. (.NOT. GPG%THERMAL_EQUILIBRIUM)) THEN
   GPG%MAXTMP = MAX(GPG%MAXTMP,MAXVAL(G%TGN(:,:,:)))
ENDIF

! Calculate variables for newton iteration
DO ISPEC = 1, NSSPEC
   GPG%NEWTON_B(ISPEC) = 1D0 + SPROP%NC(ISPEC)
   GPG%NEWTON_A(ISPEC) = SPROP%C0(ISPEC) / (GPG%NEWTON_B(ISPEC) * GPG%TREF**SPROP%NC(ISPEC))
   GPG%NEWTON_C(ISPEC) = GPG%NEWTON_A(ISPEC) * GPG%TDATUM**(SPROP%NC(ISPEC) + 1D0)
   GPG%NEWTON_D(ISPEC) = 0.5D0 * SPROP%DHMELT(ISPEC)
   GPG%NEWTON_E(ISPEC) = SPROP%TMELT(ISPEC)
   GPG%NEWTON_F(ISPEC) = MAX(SQRT(2D0*SPROP%SIGMA2MELT(ISPEC)),1D-10)
   GPG%NEWTON_G(ISPEC) = GPG%NEWTON_D(ISPEC) * DERF((GPG%TDATUM - SPROP%TMELT(ISPEC)) / GPG%NEWTON_F(ISPEC))
ENDDO

! *****************************************************************************
END SUBROUTINE INIT_GPYRO_VARS
! *****************************************************************************


! *****************************************************************************
SUBROUTINE INIT_REACTIONS
! *****************************************************************************
INTEGER :: IRXN, NRXN, NHGRXN
INTEGER :: ISPEC, NSSPEC, NGSPEC
LOGICAL :: FOUND_FROM, FOUND_TO, FOUND_REACTANT1, FOUND_REACTANT2
CHARACTER(300) :: MESSAGE
CHARACTER(3) :: THREE

NSSPEC =  SPROP%NSSPEC !Number of solid species
NGSPEC =  GPROP%NGSPEC !Number of gaseous species
NRXN   =  SPROP%NRXN   !Number of condensed-phase reactions
NHGRXN =  GPROP%NHGRXN !Number of homogeneous gaseous reactions

! Figure out condensed-phase reaction IFROM and ITO
DO IRXN = 1, NRXN
   FOUND_FROM = .FALSE.
   FOUND_TO   = .FALSE. 
   DO ISPEC = 1, NSSPEC
      IF (TRIM(RXN(IRXN)%CFROM).EQ.TRIM(SPROP%NAME(ISPEC)))THEN
         RXN(IRXN)%IFROM = ISPEC
         FOUND_FROM = .TRUE.
      ENDIF

      IF (TRIM(RXN(IRXN)%CTO  ).EQ.TRIM(SPROP%NAME(ISPEC)))THEN
         FOUND_TO = .TRUE.
         RXN(IRXN)%ITOS = ISPEC
      ENDIF

   ENDDO !ISPEC

   IF (.NOT. FOUND_FROM) THEN
      WRITE(THREE,'(I3.3)') IRXN
      MESSAGE='Error: for IRXN= ' // THREE // ', FROM species not found.'
      CALL SHUTDOWN_GPYRO(MESSAGE)
   ENDIF

   IF (.NOT. FOUND_TO   ) THEN
      IF (TRIM(RXN(IRXN)%CTO) .EQ. 'gases' .OR. TRIM(RXN(IRXN)%CTO) .EQ. 'GASES') THEN
         IF (IGPYRO_TYPE .NE. 3) WRITE(0,"(1X,A,I2,A)") "Setting up reaction ", IRXN, " as noncharring because TO='gases'"
         RXN(IRXN)%ITOS = 0
      ELSE
         WRITE(THREE,'(I3.3)') IRXN
         MESSAGE='Error: for IRXN= ' // THREE // "TO species not found. Specify either a condensed phase product or 'gases' for a noncharring reaction."
         CALL SHUTDOWN_GPYRO(MESSAGE)
      ENDIF
   ENDIF

ENDDO !IRXN

! Figure out homogeneous gas reactions reactant indices:
DO IRXN = 1, NHGRXN
   FOUND_REACTANT1 = .FALSE.
   FOUND_REACTANT2 = .FALSE. 

   DO ISPEC = 1, NGSPEC

      IF (TRIM(HGRXN(IRXN)%CREACTANT1) .EQ. TRIM (GPROP%NAME(ISPEC))) THEN
         HGRXN(IRXN)%IREACTANT1 = ISPEC
         FOUND_REACTANT1 = .TRUE.
      ENDIF

      IF (TRIM(HGRXN(IRXN)%CREACTANT2) .EQ. TRIM (GPROP%NAME(ISPEC))) THEN
         FOUND_REACTANT2 = .TRUE.
         HGRXN(IRXN)%IREACTANT2 = ISPEC
      ENDIF

   ENDDO !ISPEC

   IF (.NOT. FOUND_REACTANT1) THEN
      WRITE(THREE,'(I3.3)') IRXN
         MESSAGE='Error: for IHGRXN = '  // THREE // 'REACTANT1 not found.'
      CALL SHUTDOWN_GPYRO(MESSAGE)
   ENDIF

   IF (.NOT. FOUND_REACTANT2) THEN
      WRITE(THREE,'(I3.3)') IRXN
      MESSAGE='Error: for IHGRXN = '  // THREE // 'REACTANT2 not found.'
      CALL SHUTDOWN_GPYRO(MESSAGE)
   ENDIF
               
   ! Check the yield of reactant 1:
   IF (GPROP%HGYIELDS(HGRXN(IRXN)%IREACTANT1,IRXN) .NE. -1D0) THEN
      WRITE(THREE,'(I3.3)') IRXN
      MESSAGE='Error: for IHGRXN = '  // THREE // ' hgyield of reactant 1 must be -1'
      CALL SHUTDOWN_GPYRO(MESSAGE)
   ENDIF

ENDDO !IRXN

! *****************************************************************************
END SUBROUTINE INIT_REACTIONS
! *****************************************************************************



! *****************************************************************************
 SUBROUTINE INIT_DUMP_OUTPOUT(IMESH)
! *****************************************************************************
INTEGER, INTENT(IN) :: IMESH
INTEGER :: I, N,J
TYPE (GPYRO_MESH_TYPE), POINTER :: M

G => GPM(IMESH)
M => G%MESH

! Set FIRST_SF_IN_MESH and FIRST_PROF_IN_MESH
GPG%FIRST_SF_IN_MESH(:) = -1
DO J = 1, 100 !J is mesh #
   DO I = 1, GPG%N_SMOKEVIEW_QUANTITIES
      IF ((GPG%SMOKEVIEW_IMESH(I) .EQ. J .OR. GPG%SMOKEVIEW_IMESH(I) .EQ. 0) .AND. GPG%FIRST_SF_IN_MESH  (J) .LT. 1 ) GPG%FIRST_SF_IN_MESH  (J) = I
   ENDDO
ENDDO

GPG%FIRST_PROF_IN_MESH(:) = -1
DO J = 1, 100 !J is mesh #
   DO I = 1, GPG%N_PROFILE_QUANTITIES
      IF ((GPG%PROFILE_IMESH  (I) .EQ. J .OR. GPG%PROFILE_IMESH  (I)  .EQ. 0) .AND. GPG%FIRST_PROF_IN_MESH(J) .LT. 1) GPG%FIRST_PROF_IN_MESH(J) = I
   ENDDO
ENDDO


! Initialize point dumps:
DO I = 1, GPG%N_POINT_QUANTITIES
   ! if the the mesh to dump is not the current mesh then cylce 
   IF ( (IMESH .NE. GPG%POINT_IMESH(I)) .AND. GPG%POINT_IMESH(I) .NE. 0) CYCLE
  
   ! Start with x:
   IF (M%NCELLX .EQ. 1) THEN
      GPG%POINT_IX(I) = 1
   ELSE
      CALL GET_CLOSEST_CELL(M%NCELLX,M%X,GPG%POINT_X(I),GPG%POINT_IX(I))
   ENDIF
   
   !  And now y:
   IF (M%NCELLY .EQ. 1) THEN
      GPG%POINT_IY(I) = 1
   ELSE
      CALL GET_CLOSEST_CELL(M%NCELLY,M%Y,GPG%POINT_Y(I),GPG%POINT_IY(I))
   ENDIF

   ! And on to z:
    CALL GET_CLOSEST_CELL(M%NCELLZ,M%Z(:,GPG%POINT_IX(I),GPG%POINT_IY(I)),GPG%POINT_Z(I),GPG%POINT_IZ(I))
ENDDO

! Initialize profile dumps:
DO I = 1, GPG%N_PROFILE_QUANTITIES
   ! if the the mesh to dump is not the current mesh then cylce 
   IF ( (IMESH .NE. GPG%PROFILE_IMESH(I)) .AND. GPG%PROFILE_IMESH(I) .NE. 0) CYCLE
   G => GPM(IMESH)
   IF (GPG%PROFILE_DIRECTION(I) .EQ. 'z') THEN
      CALL GET_CLOSEST_CELL(M%NCELLX,M%X,GPG%PROFILE_COORD1(I),GPG%PROFILE_IX(I))
      CALL GET_CLOSEST_CELL(M%NCELLY,M%Y,GPG%PROFILE_COORD2(I),GPG%PROFILE_IY(I))

   ELSEIF (GPG%PROFILE_DIRECTION(I) .EQ. 'x') THEN
      CALL GET_CLOSEST_CELL(M%NCELLY,M%Y,GPG%PROFILE_COORD1(I),GPG%PROFILE_IY(I))
      CALL GET_CLOSEST_CELL(M%NCELLZ,M%Z(:,1,GPG%PROFILE_IY(I)),GPG%PROFILE_COORD2(I),GPG%PROFILE_IZ(I))

   ELSEIF (GPG%PROFILE_DIRECTION(I) .EQ. 'y') THEN
      CALL GET_CLOSEST_CELL(M%NCELLX,M%X,GPG%PROFILE_COORD1(I),GPG%PROFILE_IX(I))
      CALL GET_CLOSEST_CELL(M%NCELLZ,M%Z(:,GPG%PROFILE_IX(I),1),GPG%PROFILE_COORD2(I),GPG%PROFILE_IZ(I))
   ENDIF
ENDDO


!Initialize Smokeview dumps:
DO N = 1, GPG%N_SMOKEVIEW_QUANTITIES
   IF ( (IMESH .NE. GPG%SMOKEVIEW_IMESH(N)) .AND. GPG%SMOKEVIEW_IMESH(N) .NE. 0) CYCLE
   IF (GPG%SMOKEVIEW_PLANE(N) .EQ. 'xz') CALL GET_CLOSEST_CELL(M%NCELLY,M%Y,GPG%SMOKEVIEW_LOCATION(N),GPG%SMOKEVIEW_ICELL(N)) !y=const plane
   IF (GPG%SMOKEVIEW_PLANE(N) .EQ. 'yz') CALL GET_CLOSEST_CELL(M%NCELLX,M%X,GPG%SMOKEVIEW_LOCATION(N),GPG%SMOKEVIEW_ICELL(N)) !x=const plane
   IF (GPG%SMOKEVIEW_PLANE(N) .EQ. 'xy') CALL GET_CLOSEST_CELL(M%NCELLZ,M%Z(:,1,1),GPG%SMOKEVIEW_LOCATION(N),GPG%SMOKEVIEW_ICELL(N)) !z=const plane
ENDDO


! *****************************************************************************
END SUBROUTINE INIT_DUMP_OUTPOUT
! *****************************************************************************

!******************************************************************************
END MODULE GPYRO_INIT
!******************************************************************************